### PR TITLE
Support windows paths when resolving dependencies

### LINKED ISSUE #30: "Object.keys called on non-object" error  node -v 0.12.4 win32
Getting this on on package.json now, including dependency-check/package.json.

Object.keys(deps).forEach(function (dep) {
             ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at c:\Users\Jonathon J. Howey\AppData\Roaming\npm\node_modules\dependency-ch
eck\index.js:101:14
    at Array.forEach (native)
    at c:\Users\Jonathon J. Howey\AppData\Roaming\npm\node_modules\dependency-ch
eck\index.js:100:13

### PR DESCRIPTION
**Pull request by voxpelli**
I hope that this fixes #30, but due to lack of an actual Windows machine with a full working node setup on it I can't really test it.

@oliversalzburg Maybe you could help test this fix?

### CODE REVIEW

**Comment by oliversalzburg** [comment]
I'd be happy to test it. I just need to remember this until Monday :D Send me another @ next week if you want to make sure ;)

**Comment by oliversalzburg** [comment]
Does this help?
```
Oliver@OLIVER-HOME /p/dependency-check (master)
$ npm test

> dependency-check@2.0.0 test p:\dependency-check
> dependency-check test/

'dependency-check' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.

Oliver@OLIVER-HOME /p/dependency-check (master)
$ git checkout detect-windows-paths
Switched to branch 'detect-windows-paths'
Your branch is up-to-date with 'origin/detect-windows-paths'.

Oliver@OLIVER-HOME /p/dependency-check (detect-windows-paths)
$ npm test

> dependency-check@2.5.0 test p:\dependency-check
> standard && node cli.js test/

Success! All dependencies used in the code are listed in package.json

Oliver@OLIVER-HOME /p/dependency-check (detect-windows-paths)
```

**Comment by voxpelli** [comment]
@oliversalzburgThe first test failure there looks weird – not what I would expect. Perhaps you could try this one with the failed test you experienced in https://github.com/voxpelli/node-promised-retry/pull/3#issuecomment-133104609 ?

**Comment by oliversalzburg** [comment]
@voxpelli Good idea. Works great in there.

**Comment by oliversalzburg** [comment]
@voxpelli I've also verified this with a global installation of dependency-check on my Windows workstation. Seems to work fine.

**Comment by maxogden** [comment]
@voxpelli nice work, this looks like quite the annoying bug

**Comment by ghaiklor** [comment]
@maxogden when will this update be merged and published ? I'm using your module in my generator-sails-rest-api and users can't run it on Windows machines due this bug. Thanks.

**Comment by maxogden** [comment]
@ghaiklor its out as 2.5.1

**Comment by ghaiklor** [comment]
@maxogden thanks :+1:

**Comment by oliversalzburg** [comment]
Nice :+1:

**Pull request merged**
